

<script type="text/javascript">
    window.WebPlatform = window.WebPlatform || {};
    WebPlatform.Phrases = (WebPlatform.merge || window.mergeUnique)({
        'ERR_INVALID_REQUEST': 'Invalid request!',
        'label.invalid_request': "¡Solicitud no válida!",
        'client.by': "por",
        'client.on': "el",
        'client.in': "en",
        'label.of': "de",
        'client.comment': "Comentario",
        'client.comments': "Comentarios",
        'client.read_more': "Leer más",
        'client.load_more': "Cargar más",
        'label.view': "Ver",
        'label.years': "Años",
        'label.months': "Meses",
        'label.days': "Días",
        'label.minutes': "Minutos",
        'label.hours': "Horas",
        'label.seconds': "Segundos",
        'card.number': "Número de tarjeta",
        'card.cvc': "CVC",
        'card.mm': "MM",
        'card.yyyy': "AAAA",
        'card.invalid_data': "Por favor, verifica los datos de tu tarjeta de crédito/débito e inténtalo de nuevo.",
        'card.invalid_number': "El número de tarjeta no es un número válido de tarjeta de crédito o débito.",
        'card.invalid_month': "El mes de caducidad de tu tarjeta no es válido.",
        'card.invalid_year': "El año de caducidad de tu tarjeta no es válido.",
        'card.invalid_cvc': "El código de seguridad de tu tarjeta no es válido.",
        'card.unknown_error': "Por favor, verifica tus datos de pago y vuelve a intentarlo.",
        'label.shipping_address': "Dirección de envío",
        'label.billing_address': "Dirección de facturación",
        'label.january': "Enero",
        'label.february': "Febrero",
        'label.march': "Marzo",
        'label.april': "Abril",
        'label.may': "Mayo",
        'label.june': "Junio",
        'label.july': "Julio",
        'label.august': "Agosto",
        'label.september': "Septiembre",
        'label.october': "Octubre",
        'label.november': "Noviembre",
        'label.december': "Diciembre",
        'label.jan': "Ene",
        'label.feb': "Feb",
        'label.mar': "Mar",
        'label.apr': "Abr",
        'label.may_short': "Mayo",
        'label.jun': "Jun",
        'label.jul': "Jul",
        'label.aug': "Ago",
        'label.sep': "Sep",
        'label.oct': "Oct",
        'label.nov': "Nov",
        'label.dec': "Dic",
        'label.add_to_cart': "Añadir al carrito",
        'label.buy_now': "Comprar ahora",
        'label.update': "Actualizar",
        'label.change': "Cambiar",
        'label.month': "mes",
        'label.year': "año",
        'label.months_lower': "meses",
        'label.years_lower': "años",
        'label.week_lower': "semana",
        'label.weeks_lower': "semanas",
        'label.saving': "Ahorro",
        'label.checkout_now': "Pagar ahora",
        'label.view_cart': "Ver carrito",
        'label.select_product_variant': "Seleccionar variación",
        'err.select_product_variants': "Selecciona la variación para cada artículo de tu pedido",
        'label.cod': "Pago contra entrega",
        'label.bank': "Transferencia bancaria",
        'label.yes': "SÍ",
        'label.no': "NO",
        'label.enter_delivery_address': "Introduce tus datos de envío",
        'label.no_delivery_offices': "No hay oficinas disponibles",
        'label.select_speedy_office': "Seleccionar oficina de Speedy",
        'label.no_shipping_services': "Introduce la dirección",
        'label.select_delivery_type': "Selecciona el tipo de entrega",
        'label.monday_min': "L",
        'label.tuesday_min': "M",
        'label.wednesday_min': "X",
        'label.thursday_min': "J",
        'label.friday_min': "V",
        'label.saturday_min': "S",
        'label.sunday_min': "D",
        'label.monday_short': "Lun",
        'label.tuesday_short': "Mar",
        'label.wednesday_short': "Miér",
        'label.thursday_short': "Jue",
        'label.friday_short': "Vie",
        'label.saturday_short': "Sáb",
        'label.sunday_short': "Dom",
        'label.contact_booked_error': "Ya has reservado una plaza en este evento de grupo",
        'label.already_booked_time_error': "La hora seleccionada no está disponible, por favor selecciona otra hora",
        'label.booking_notice_error': "La reserva está demasiado cerca de la hora actual. Por favor, recarga la página",
        'label.delete_account_prompt': "¿Quieres eliminar tu cuenta?",
        'label.slots_left': "plazas restantes",
        'store.label.sale': "Oferta",
        'label.left_in_stock_multiple': "¡Solo quedan %x% en stock!",
        'label.left_in_stock_single': "¡Solo queda 1 en stock!",
        'label.taxes': "Impuesto:",
        'label.taxes_included': "Impuesto incluido:",
        'error.fill_required_fields': "Por favor, completa todos los campos obligatorios.",
        'label.logout': "Cerrar sesión",
        'label.subscriptions': "Suscripciones",
        'label.my_membership': "Mis membresías",
        'label.downloads': "Descargas",
        'label.order_history': "Historial de pedidos",
        'label.details': "Detalles",
        'label.address': "Dirección",
        'label.information': "Detalles",
        'label.name': "Nombre",
        'label.email': "Dirección de e-mail",
        'label.password': "Contraseña",
        'label.old_password': "Contraseña actual",
        'label.new_password': "Nueva contraseña",
        'label.repeat_password': "Repetir contraseña",
        'members.button.delete_account': "Eliminar perfil",
        'members.button.save_changes': "Guardar cambios",
        'label.saved': "¡Guardado!",
        'label.phone': "Teléfono",
        'label.optional': "opcional",
        'label.store.address': "Dirección",
        'label.store.address2': "Información adicional sobre la dirección",
        'label.store.city': "Ciudad",
        'label.store.state': "Provincia",
        'label.store.post_code': "Código postal",
        'label.store.companyId': "Núm. de identificación de empresa",
        'label.store.companyName': "Nombre de empresa",
        'label.store.use_different_billing_addr': "Utilizar una dirección de facturación diferente",
        'label.download': "Descargar",
        'label.my_subscriptions': "Mis suscripciones",
        'label.product': "Producto",
        'label.subscription_fee': "Cuota de suscripción",
        'label.last_billing_date': "Última fecha de facturación",
        'label.next_billing_date': "Próxima fecha de facturación",
        'label.order_status_canceled': "Cancelado",
        'label.order_status_completed': "Finalizado",
        'label.cancel_subscription': "Cancelar suscripción",
        'label.view_membership': "ver detalles de membresía",
        'label.cancel_subscription_desc': "¿Seguro que quieres cancelar tu suscripción?",
        'label.invoice_no': "Factura núm.",
        'label.date': "Fecha",
        'label.store.total': "Total",
        'label.status': "Estado",
        'label.no_orders_yet': "Todavía no tienes ningún pedido",
        'label.status_pending': "Pendiente",
        'label.status_shipped': "Enviado",
        'label.status_completed': "Finalizado",
        'label.status_canceled': "Cancelado",
        'label.shipping_details': "Detalles de envío",
        'label.billing_details': "Datos de facturación",
        'label.payment_details': "Datos de pago",
        'label.card': "Tarjeta de crédito",
        'label.shipping_cost': "Gastos de envío",
        'label.additional_info': "Información adicional",
        'label.discount': "Descuento",
        'label.quantity': "Cantidad",
        'label.price': "Precio",
        'label.variation': "Variación"

    }, WebPlatform.Phrases || {});
</script>
<script type="text/javascript">
    WebPlatform.Store = WebPlatform.Store || {};

    WebPlatform.merge(WebPlatform.Store, {
        hideUnavailableVariations: false,
        notEnoughQuantityMessage: "No hay suficiente cantidad disponible para algunos de los productos.",
        currencySymbol: "$",
        currencySymbolAtLeft: true,
        currency: 'USD',
        priceWithTax: true,
        country: 'EC',
        baseUrl: '/store',
        productAddedToCart: 'El producto se ha añadido a tu carrito',
        fbPxId: '1024585225579109'
    });

    WebPlatform.Funnels = WebPlatform.Funnels || {};
    WebPlatform.Funnels.hideProductLinks = true;
    WebPlatform.Funnels.showCheckoutButton = true;
    WebPlatform.Funnels.checkoutButtonTarget = "https://steviabygreenlife.com/store/checkout";
    WebPlatform.Funnels.variant = "lxygUz7FH73amznfzGyGPw==";
    WebPlatform.Funnels.steps = [
        /**/
        {
            type: 'PAGE',
            host: '',
            base: 'funnel',
            url: 'steviabygreenlife',
            id: 1,
            kind: 'REGULAR',
            funnelId: 1
        },
        /**/
    ];


    WebPlatform.clientData = null;
    WebPlatform.visitorEmail = '';
    WebPlatform.visitorName = '';
</script>

{{-- <script type="text/javascript" src="{{ asset('scripts/platform.client.min.js') }}" data-cookieconsent="ignore"></script> --}}

<script type="text/javascript" src="{{asset('scripts/common/hit.js')}}?v={{ config('app.website_version')}}"></script>

